name: amplicnv-pipeline
channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - snakemake=6.6.1
  - bedtools=2.30.0
  - pybedtools=0.8.2
  - openpyxl=3.0.7
  - seaborn=0.11.1
  - pip=21.2.2
  - pip:
    - amplicnv
