name: amplicnv-pipeline
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - snakemake=6.6.1
  - bedtools=2.30.0
  - pybedtools=0.8.1
  - openpyxl=2.6.1
  - seaborn=0.11.1
  - pip
  - pip:
    - cnvfinder
